apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: customer-service
  name: customer-service-controller
spec:
  replicas: 2
  selector:
    name: customer-service
  template:
    metadata:
      labels:
        name: customer-service
    spec:
      containers:
      - image: teixeirafernando/customer-service-kubernetes:latest
        name: customer-service
        ports:
        - containerPort: 8081
          name: http-server