apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    name: customer-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: customer-service