name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

jobs:
  ci_verification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        working-directory: ./customer-service
        run: npm ci

      - name: Test Customer Service - unit tests
        working-directory: ./customer-service
        run: npm run test:unit

      - name: Docker-compose - run application
        run: docker-compose up -d --force-recreate --no-deps
        
      - name: Test Customer Service - integration tests
        working-directory: ./customer-service
        run: npm run test:integration
